name: smart_video_cast
description: smart_video_cast let you discover cast devices like Chrome Cast and Apple TV and connect to them.
version: 1.0.2
homepage: https://github.com/smarthost-tr/smart_video_cast

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter

  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.smarthost.smart_video_cast
        pluginClass: SmartVideoCastPlugin
      ios:
        pluginClass: SmartVideoCastPlugin
